name: manage-azure-policy-df7b365c
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Azure_Key_Vault_Managed_HSM_Keys_should_have_more_than_the_specified_number_of_days_before_expiration_ad27588c-0198-4c84-81ef-08efd0274653/**'
#      - .github/workflows/manage-azure-policy-df7b365c.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_df7b365c}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Azure_Key_Vault_Managed_HSM_Keys_should_have_more_than_the_specified_number_of_days_before_expiration_ad27588c-0198-4c84-81ef-08efd0274653/**
